"""Confound control plane (spec §40): conditions A-I, scaffolding matching, compute accounting."""

from .compute import (
    ACCOUNTING_POLICY_ID,
    WEIGHTS,
    ComputeLedger,
    ComputeMatchError,
    matched_budget,
    reconcile_search_only,
)
from .flops import (
    CURRENCY_ID,
    DEFAULT_CURRENCY,
    DEFAULT_POLICY as DEFAULT_FLOPS_POLICY,
    DeviceSecondsPolicy,
    FlopsPolicy,
    MatchReport,
    TaskAttempt,
    matched_flops,
    pass_at_c_curve,
    solve_rate_at_fixed_device_seconds,
    solve_rate_at_fixed_flops,
)
from .plane import (
    CONFOUNDS,
    REQUIRED_CONTROLS,
    ROLES,
    Condition,
    ConditionPlaneError,
    ResidualConfound,
    build_conditions,
    check_condition_f,
)
from .scaffolding import (
    Scaffolding,
    ScaffoldingMatcher,
    ScaffoldingReport,
    ScaffoldingResidual,
    scaffolding_is_equalized,
)

__all__ = [
    "ACCOUNTING_POLICY_ID",
    "CONFOUNDS",
    "REQUIRED_CONTROLS",
    "ROLES",
    "WEIGHTS",
    "ComputeLedger",
    "ComputeMatchError",
    "Condition",
    "DEFAULT_FLOPS_POLICY",
    "CURRENCY_ID",
    "DEFAULT_CURRENCY",
    "DeviceSecondsPolicy",
    "FlopsPolicy",
    "MatchReport",
    "TaskAttempt",
    "matched_flops",
    "pass_at_c_curve",
    "solve_rate_at_fixed_device_seconds",
    "solve_rate_at_fixed_flops",
    "ConditionPlaneError",
    "ResidualConfound",
    "Scaffolding",
    "ScaffoldingMatcher",
    "ScaffoldingReport",
    "ScaffoldingResidual",
    "build_conditions",
    "check_condition_f",
    "matched_budget",
    "reconcile_search_only",
    "scaffolding_is_equalized",
]
