"""The ten acceptance tests from the assurance integration spec §14.

Each test below is one numbered acceptance criterion, in order, quoted in its docstring.
"""

from __future__ import annotations

import pytest

from bestsad.assurance import (
    ASSURANCE_LIFECYCLE,
    AssuranceCertificate,
    AssuranceLedger,
    ClaimState,
    DependencyEdge,
    DependencyType,
    K0_ROOT,
    BSIR_ROOT,
    EVALUATOR_ROOT,
    LedgerViolation,
    LifecycleViolation,
    PolicyGate,
    PromotionContext,
    SelfPromotionRefused,
    Warrant,
    advance_lifecycle,
    capability_claim,
    current_roots,
    evaluate,
    make_claim,
    make_evidence,
    negative_result_claim,
    primitive_effect_claims,
    semantic_equivalence_claim,
)
from bestsad.assurance.claims import CAPABILITY, NEGATIVE_RESULT, SEMANTIC_EQUIVALENCE
from bestsad.genomes import Primitive
from bestsad.kernel import INT, TList, app, const_int, lam, var


def _primitive(name: str = "prim:sum") -> Primitive:
    body = app("fold", lam((("acc", INT), ("e", INT)), app("add", var("acc"), var("e"))),
               const_int(0), var("xs"))
    return Primitive(name, ("xs",), body, (TList(INT),), INT, origin="utility")


def _roots():
    return current_roots(preregistration_hash="a" * 64, benchmark_manifest_id="bm:test")


def _certificate(claim_id: str, status: str = "PASS", warrant=Warrant.EMPIRICAL):
    return AssuranceCertificate(
        certificate_id=f"cert:{claim_id[-8:]}", claim_id=claim_id,
        verifier="bestsad.assurance", status=status, warrant=warrant,
    )


def _capability(producer="bestsad.experiments.analysis"):
    roots = _roots()
    evidence = [
        make_evidence("preregistration", "docs/preregistrations", "hash", Warrant.FORMAL, {"h": 1}),
        make_evidence("condition_manifest", "conditions", "manifest", Warrant.DIRECT_OBSERVATION, {}),
        make_evidence("compute_ledger", "telemetry", "ledger", Warrant.DIRECT_OBSERVATION, {}),
        make_evidence("causal_attribution", "causal", "ablation", Warrant.EMPIRICAL, {}),
    ]
    claim = capability_claim(
        roots=roots, producer=producer,
        statement="Evolved representation improves verified compositional OOD synthesis",
        treatment_condition="D", comparators=["A", "F", "G", "H", "I"],
        effect_metric="verified_ood_solve_rate_per_compute", effect=0.08, ci=(0.03, 0.13),
        preregistration_content_id="prereg:x", compute_ledger_id="ledger:x",
        causal_attribution_refs=["attr:1"], evidence=evidence,
    )
    return claim, roots


def _full_context(claim, roots, **overrides):
    base = dict(
        certificate=_certificate(claim.claim_id),
        dependency_states={d: "active" for d in claim.dependency_refs},
        active_assumptions={a: roots.values.get(a, "x") for a in claim.assumption_refs},
        current_source_hashes=dict(roots.values),
        satisfied_conditions=("F", "H", "I"),
        defeated_conditions=("F", "H", "I"),
        concentration_pass=True,
        policy_allows=True,
    )
    base.update(overrides)
    return PromotionContext(**base)


# --- 1 -----------------------------------------------------------------------------------------


def test_1_evolution_agent_cannot_promote_its_own_primitive_to_core():
    """"A primitive generated by the evolution agent cannot promote itself to CORE." """
    # The lifecycle refuses the step outright for a non-gate actor.
    with pytest.raises(LifecycleViolation, match="promotion gate"):
        advance_lifecycle("EXPERIMENTALLY_SUPPORTED", "CORE_ELIGIBLE", actor_is_gate=False)
    with pytest.raises(LifecycleViolation, match="promotion gate"):
        advance_lifecycle("CORE_ELIGIBLE", "CORE", actor_is_gate=False)
    # ...and permits it for a gate.
    assert advance_lifecycle("CORE_ELIGIBLE", "CORE", actor_is_gate=True) == "CORE"

    # The gate itself refuses to act when it *is* the producer.
    primitive = _primitive()
    roots = _roots()
    claim, _ev = semantic_equivalence_claim(
        primitive, roots=roots, producer="evolution-agent", differential_cases=1000
    )
    gate = PolicyGate(actor="evolution-agent")
    with pytest.raises(SelfPromotionRefused, match="own promotion"):
        gate.decide(claim, PromotionContext())


def test_1b_ledger_refuses_a_producer_written_promoted_state():
    ledger = AssuranceLedger()
    primitive = _primitive()
    roots = _roots()
    claim, evidence = semantic_equivalence_claim(
        primitive, roots=roots, producer="evolution-agent", differential_cases=1000
    )
    for e in evidence:
        ledger.add_evidence(e)
    ledger.add_claim(claim)
    with pytest.raises(LedgerViolation, match="PolicyGate"):
        ledger.record_state(claim.claim_id, ClaimState.PROMOTED, actor="evolution-agent")


# --- 2 -----------------------------------------------------------------------------------------


def test_2_changing_a_semantic_root_stales_every_dependent_claim():
    """"Changing K0 or BSIR semantic-root content ID stales every dependent primitive/genome
    claim." """
    ledger = AssuranceLedger()
    roots = _roots()
    primitive = _primitive()
    claim, evidence = semantic_equivalence_claim(
        primitive, roots=roots, producer="extractor", differential_cases=5000
    )
    for e in evidence:
        ledger.add_evidence(e)
    ledger.add_claim(claim)

    # A genome claim depending on the primitive claim, and a capability claim on the genome.
    genome_claim = make_claim(
        "genome_validity", "Genome G uses only admitted primitives.",
        producer="genome-builder", warrant=Warrant.RIGOROUS_COMPUTATION,
        evidence=[evidence[0]], dependencies=[claim.claim_id], assumptions=[K0_ROOT],
    )
    ledger.add_claim(genome_claim)
    cap, _ = _capability()
    cap = type(cap)(**{**cap.__dict__, "dependency_refs": (genome_claim.claim_id,)}) \
        if hasattr(cap, "__dict__") else cap
    from dataclasses import replace
    cap = replace(cap, dependency_refs=(genome_claim.claim_id,))
    ledger.add_claim(cap)

    events = ledger.invalidate_from(K0_ROOT, reason="K0 semantics changed")
    affected = {e.node_id for e in events}
    assert claim.claim_id in affected
    assert genome_claim.claim_id in affected, "staleness must reach the genome claim"
    assert cap.claim_id in affected, "staleness must reach the capability claim transitively"
    assert all(e.new_state is ClaimState.STALE for e in events)

    # Nothing was deleted: history remains queryable (§1.5).
    assert ledger.claims[claim.claim_id].status is ClaimState.STALE
    assert ledger.history(claim.claim_id), "the claim's history must survive invalidation"


# --- 3 -----------------------------------------------------------------------------------------


def test_3_evaluator_integrity_failure_invalidates_capability_claims():
    """"A hidden-evaluator integrity failure invalidates affected capability claims." """
    ledger = AssuranceLedger()
    cap, roots = _capability()
    ledger.add_claim(cap)
    events = ledger.invalidate_from(
        EVALUATOR_ROOT, reason="hidden-test leak detected", quarantine=True
    )
    assert cap.claim_id in {e.node_id for e in events}
    assert ledger.claims[cap.claim_id].status is ClaimState.QUARANTINED
    # Quarantine, not staleness: an integrity breach is not merely out of date.
    assert all(e.new_state is ClaimState.QUARANTINED for e in events)


# --- 4 -----------------------------------------------------------------------------------------


@pytest.mark.parametrize("missing", ["F", "H", "I"])
def test_4_missing_control_blocks_a_capability_claim_however_high_the_accuracy(missing):
    """"Missing F, H or I prevents a confirmatory capability claim even if treatment accuracy
    is high." """
    claim, roots = _capability()
    present = tuple(c for c in ("F", "H", "I") if c != missing)
    verdict = evaluate(
        claim,
        _full_context(claim, roots, satisfied_conditions=present, defeated_conditions=present,
                      gate_actor="policy-gate"),
    )
    assert not verdict.promotable
    assert any(missing in b and "missing" in b for b in verdict.blockers)


def test_4b_a_control_that_matches_the_treatment_also_blocks_the_claim():
    """§8: "missing/failed F blocks representation-capability promotion" — failed counts too."""
    claim, roots = _capability()
    verdict = evaluate(
        claim,
        _full_context(claim, roots, defeated_conditions=("F", "H"), gate_actor="policy-gate"),
    )
    assert not verdict.promotable
    assert any("matched or beat the treatment" in b for b in verdict.blockers)


# --- 5 -----------------------------------------------------------------------------------------


def test_5_condition_g_may_beat_the_treatment_and_is_reported_without_special_handling():
    """"Condition G may beat the treatment and the system reports it without special
    handling." """
    claim, roots = _capability()
    # G is a reference class, not one of the required confound controls, so it never appears in
    # the promotion predicate's required set — there is no code path that special-cases it.
    from bestsad.assurance.claims import CLAIM_CLASSES

    assert "G" not in CLAIM_CLASSES[CAPABILITY].required_conditions
    verdict = evaluate(claim, _full_context(claim, roots, gate_actor="policy-gate"))
    assert verdict.promotable, "G beating the treatment must not itself block promotion"
    # And the analysis reports G's margin alongside, which is asserted in tests/experiments.


# --- 6 -----------------------------------------------------------------------------------------


def test_6_ablation_must_re_expand_to_k0_equivalent_semantics():
    """"An ablated primitive re-expands to K0-equivalent semantics before causal effect is
    accepted." """
    from bestsad.bsir import semantic_hash
    from bestsad.causal import ablate
    from bestsad.kernel import Kernel, Program, Term

    primitive = _primitive("prim:double")
    expansion = app("mul", var("a"), const_int(2))
    p = Primitive("prim:double", ("a",), expansion, (INT,), INT)
    kernel = Kernel({p.primitive_id: (p.params, p.expansion)})
    program = Program((("x", INT),), Term("prim:double", (var("x"),)), INT)
    ablated = ablate(program, "prim:double", kernel)
    assert semantic_hash(ablated, kernel) == semantic_hash(program, kernel)

    # The per-primitive claim carries the ablation as evidence with an EMPIRICAL warrant.
    from bestsad.stats import Interval
    from bestsad.causal import PrimitiveEffect

    effect = PrimitiveEffect(
        primitive_id="prim:double", semantic_hash="abc",
        direct_effect=Interval(0.02, 0.0, 0.04), indirect_effect=Interval(0.0, 0.0, 0.0),
        cross_family_reuse=3, shortcut_shaped=False, compression_shaped=False,
        semantic_gain_v2=4.0,
    )
    claims = primitive_effect_claims([effect], roots=_roots(), producer="causal-plane")
    assert len(claims) == 1
    claim, evidence = claims[0]
    kinds = {e.kind for e in evidence}
    assert "paired_ablation" in kinds and "semantic_gain" in kinds


# --- 7 -----------------------------------------------------------------------------------------


def test_7_a_compression_only_primitive_cannot_be_promoted_as_capability_evidence():
    """"A compression-only primitive can be useful but cannot be promoted as generalized
    capability evidence." """
    roots = _roots()
    # A claim whose only warrant is heuristic/asserted can never carry a capability promotion.
    claim = make_claim(
        CAPABILITY, "Compression implies capability.", producer="compressor",
        warrant=Warrant.HEURISTIC,
        evidence=[make_evidence("preregistration", "p", "m", Warrant.HEURISTIC, {})],
    )
    verdict = evaluate(claim, _full_context(claim, roots, gate_actor="policy-gate"))
    assert not verdict.promotable
    assert any("never on its own" in b for b in verdict.blockers)
    assert any("not sufficient for claim class" in b for b in verdict.blockers)


# --- 8 -----------------------------------------------------------------------------------------


def test_8_a_null_exp001_produces_a_promotable_negative_result_claim():
    """"A null EXP-001 produces a promoted negative-result ClaimObject when the experiment is
    valid." """
    roots = _roots()
    evidence = [
        make_evidence("experiment_manifest", "artifacts", "manifest", Warrant.DIRECT_OBSERVATION, {}),
        make_evidence("report", "docs/experiments", "report", Warrant.EMPIRICAL, {}),
    ]
    claim = negative_result_claim(
        roots=roots, producer="bestsad.experiments.analysis",
        statement="EXP-001-DR does not support the target effect.",
        search_space_constraint="Abstractions mined from solved curriculum programs are bounded "
                                "by what the searcher already solves.",
        preregistration_content_id="prereg:x", evidence=evidence, outcome_class="h0_consistent",
    )
    # A negative result does not require the controls to have been *beaten* — only that the
    # experiment was valid — because the claim being made is about the absence of an effect.
    context = _full_context(claim, roots, satisfied_conditions=(), defeated_conditions=(),
                            gate_actor="policy-gate")
    verdict = evaluate(claim, context)
    assert verdict.promotable, f"negative result should be promotable: {verdict.blockers}"

    ledger = AssuranceLedger()
    for e in evidence:
        ledger.add_evidence(e)
    ledger.add_claim(claim)
    ledger.add_certificate(_certificate(claim.claim_id))
    gate = PolicyGate(actor="policy-gate")
    verdict, decision = gate.decide(claim, context)
    assert decision is not None
    promoted = ledger.apply_decision(decision)
    assert promoted.status is ClaimState.PROMOTED


# --- 9 -----------------------------------------------------------------------------------------


def test_9_report_generation_consumes_the_central_promotion_predicate():
    """"Report generation consumes the central promotion predicate rather than duplicating its
    own rules." """
    import inspect

    from bestsad.stats import preregistration as prereg_module

    source = inspect.getsource(prereg_module.ReportGate)
    assert "_assurance_verdict" in source
    assert "from ..assurance.promotion import PromotionContext, evaluate" in source
    # The duplicated rule bodies are gone from the report gate.
    assert "no capability claim without conditions" not in source, (
        "the F/H/I rule must live in the promotion predicate, not be re-implemented here (§8)"
    )


def test_9b_the_report_gate_still_refuses_what_it_must():
    """Delegation must not weaken the gate: the refusals still fire, now via the predicate."""
    from bestsad.stats import ClaimRequest, Preregistration, ReportGate, ReportRefused

    prereg = Preregistration(
        experiment_id="X", primary_endpoint="e",
        conditions=({"condition_id": c} for c in "ABCDEFGHI"),
        seeds_per_condition=8, minimum_interesting_effect={"x": 1},
        multiple_comparison_control={"method": "benjamini_hochberg", "level": 0.05,
                                     "family": ["a"]},
        stopping_rule="fixed", declared_outcome_interpretations={"positive": "p"},
        power_analysis={"powered": True},
    )
    prereg.conditions = tuple(prereg.conditions)
    prereg.commit()
    request = ClaimRequest(
        experiment_id="X", claim_kind="capability",
        conditions_run=("A", "D", "F", "H"),   # I missing
        treatment_beats={"F": True, "H": True, "I": True},
        compression_ratio=1.5, capability_delta=0.08,
        fdr_controlled=True, concentration_test_passed=True, powered=True,
    )
    with pytest.raises(ReportRefused, match="missing I"):
        ReportGate(prereg).certify(request)


# --- 10 ----------------------------------------------------------------------------------------


def test_10_stale_semantic_certificates_fail_closed_for_core_use():
    """"Stale semantic certificates make compiler/runtime CORE use fail closed." """
    from bestsad.assurance.objects import NON_EXECUTABLE_STATES

    roots = _roots()
    primitive = _primitive()
    claim, evidence = semantic_equivalence_claim(
        primitive, roots=roots, producer="extractor", differential_cases=10_000, exhaustive=True
    )
    from dataclasses import replace

    stale = replace(claim, status=ClaimState.STALE)
    assert stale.status in NON_EXECUTABLE_STATES

    verdict = evaluate(stale, _full_context(stale, roots, gate_actor="policy-gate"))
    assert not verdict.promotable
    assert any("STALE" in b for b in verdict.blockers)


def test_10b_a_moved_root_makes_a_claim_fail_closed_even_before_propagation():
    """Defence in depth: the predicate compares recorded source hashes to live ones, so a claim
    whose root moved fails even if nobody has run invalidation yet."""
    claim, roots = _capability()
    moved = dict(roots.values)
    moved[K0_ROOT] = "k0:something-else"
    verdict = evaluate(
        claim, _full_context(claim, roots, current_source_hashes=moved, gate_actor="policy-gate")
    )
    assert not verdict.promotable
    assert any("source/content hashes have moved" in b for b in verdict.blockers)
